# Generated by Django 3.2.8 on 2021-11-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningplateform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('length', models.PositiveIntegerField(blank=True, default=0)),
                ('credit_hours', models.PositiveIntegerField(blank=True, choices=[(0, '---Please select credit hour---'), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], default=0)),
                ('module_order', models.TextField(blank=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learningplateform.program')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='learningplateform.course')),
                ('plo_addressed', models.ManyToManyField(blank=True, related_name='plo_addressed', to='learningplateform.ProgramOutcome')),
            ],
            options={
                'verbose_name': 'Course Outcome',
                'verbose_name_plural': 'Course Outcomes',
                'db_table': 'course_outcome',
            },
        ),
    ]
