version: "3.9"

services:
  redis:
    image: "redis:alpine"
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=foresite
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5434"
  web:
    container_name: social_media_django
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      # - postgres
      - redis
      - db
    # links:
    #   - postgres

volumes:
  db-data: