# Generated by Django 3.2.8 on 2021-11-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Crime', 'Crime'), ('Fantacy', 'Fantacy'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('True Story', 'True Story')], max_length=100)),
            ],
        ),
    ]
