# Generated by Django 3.2.9 on 2021-11-15 06:56

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeLocationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_latitude', models.DecimalField(decimal_places=15, max_digits=50)),
                ('destination_longitude', models.DecimalField(decimal_places=15, max_digits=50)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
    ]
