# Generated by Django 3.2.8 on 2021-11-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add notification title here.', max_length=255)),
                ('message', models.TextField(blank=True, help_text='Add notification message here.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image view on recived notification.', null=True, upload_to='notification-image')),
            ],
            options={
                'verbose_name': 'Send Push Notification',
                'verbose_name_plural': 'Send Push Notifications',
                'db_table': 'push_notification',
            },
        ),
    ]
