# Generated by Django 3.2.8 on 2021-11-15 08:55

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pushnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_latitude', models.DecimalField(decimal_places=15, max_digits=50)),
                ('destination_longitude', models.DecimalField(decimal_places=15, max_digits=50)),
                ('location', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
    ]
