# Generated by Django 3.2.8 on 2021-11-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_maphistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFilesUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Files', models.FileField(upload_to='upload/Excel')),
            ],
        ),
        migrations.AlterModelOptions(
            name='maphistory',
            options={'verbose_name': 'Map History', 'verbose_name_plural': 'Map History'},
        ),
    ]
